name: build_test_publish_aarch64
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  release:
    types: [created]
  schedule:
    - cron:  '0 12 * * *'
jobs:
  build_test_publish_linux:
    name: ${{ matrix.python-version }} on linux-aarch64
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["python3.10",
                         "python3.9",
                         "python3.8",
                         "python3.7",
                         "python3.6"]

    steps:
    - uses: actions/checkout@v2

    - name: Install Prerequisites
      run: |
        sudo apt-get update
        sudo apt-get -y install python3-pip autoconf automake libtool pkg-config gettext libjson-c-dev libpcap-dev
        sudo apt-get -y install libusb-1.0-0-dev libdbus-glib-1-dev libbluetooth-dev libnl-genl-3-dev flex bison

    - name: Installing NFStream requirements
      run: |
        ${{ matrix.python-version }} -m pip install -r dev_requirements.txt

    - name: Build Engine dependencies
      run: |
        git clone --branch libgpg-error-1.42 https://github.com/gpg/libgpg-error
        cd libgpg-error
        ./autogen.sh
        ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc --disable-nls
        make
        sudo make install
        cd ..
        rm -rf libgpg-error
        git clone --branch libgcrypt-1.8.8 https://github.com/gpg/libgcrypt
        cd libgcrypt
        ./autogen.sh
        ./configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc
        make
        sudo make install
        cd ..
        rm -rf libgcrypt
        git clone --branch fanout https://github.com/tsnoam/libpcap
        cd libpcap
        ./configure --enable-ipv6 --disable-universal --enable-dbus=no --without-libnl
        make
        sudo make install
        cd ..
        rm -rf libpcap
        git clone --branch dev https://github.com/ntop/nDPI.git
        cd nDPI
        ./autogen.sh --with-local-libgcrypt
        ./configure
        make
        sudo mkdir /usr/local/include/ndpi
        sudo cp -a src/include/. /usr/local/include/ndpi/
        sudo cp example/ndpiReader /usr/local/bin/ndpiReader
        sudo cp src/lib/libndpi.a /usr/local/lib/libndpi.a
        cd ..
        rm -rf nDPI
        ${{ matrix.python-version }} setup.py bdist_wheel

    - name: Generated wheel
      run: |
        ls dist/

    - name: Testing and coverage report generation
      run: |
        ${{ matrix.python-version }} -m coverage run tests.py
        ${{ matrix.python-version }} -m coverage combine

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    - name: Publish on Pypi
      if: startsWith(github.ref, 'refs/tags/')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload --skip-existing dist/*.whl
