name: build_test_publish_windows
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  release:
    types: [created]
  schedule:
    - cron:  '0 12 * * *'
jobs:
  build_test_publish_windows:
    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        python-version: [3.9, 3.8, 3.7, 3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git mingw-w64-x86_64-toolchain automake1.16 automake-wrapper autoconf libtool make mingw-w64-x86_64-json-c

    - name: Print Python version
      run: |
        python -c "import sys; print(sys.version)"

    - name: Install NFStream requirements
      run: |
         python -m pip install -r dev_requirements.txt

    - name: Build Engine dependencies
      run: |
         choco install wget --no-progress
         wget --user ${{ secrets.NPCAP_OEM_USERNAME }} --password ${{ secrets.NPCAP_OEM_PASSWORD }} https://nmap.org/npcap/oem/dist/npcap-1.55-oem.exe
         Start-Process npcap-1.55-oem.exe -ArgumentList "/loopback_support=yes /winpcap_mode=yes /dot11_support=yes /S" -wait
         msys2 -c 'git clone --branch libgpg-error-1.42 https://github.com/gpg/libgpg-error'
         msys2 -c 'cd libgpg-error'
         msys2 -c './autogen.sh'
         msys2 -c './configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc --disable-nls'
         msys2 -c 'make'
         msys2 -c 'make install'
         msys2 -c 'cd ..'
         msys2 -c 'rm -rf libgpg-error/'
         msys2 -c 'git clone --branch libgcrypt-1.8.8 https://github.com/gpg/libgcrypt'
         msys2 -c 'cd libgcrypt'
         msys2 -c './autogen.sh'
         msys2 -c './configure -enable-maintainer-mode --enable-static --enable-shared --with-pic --disable-doc'
         msys2 -c 'make'
         msys2 -c 'make install'
         msys2 -c 'cd ..'
         msys2 -c 'rm -rf libgcrypt/'
         msys2 -c 'git clone --branch dev https://github.com/ntop/nDPI.git'
         msys2 -c 'cd nDPI'
         msys2 -c './autogen.sh'
         msys2 -c 'make all'
         New-Item -Path "..\nfstream\engine\" -Name "ndpi_includes" -ItemType "directory"
         msys2 -c 'cp -a src/include/. ../nfstream/engine/ndpi_includes/'
         msys2 -c 'ls src/lib/'
         msys2 -c 'cp src/lib/libndpi.a ../nfstream/engine/libndpi.a'
         msys2 -c 'cd ..'
         msys2 -c 'rm -rf nDPI/'
         msys2 -c 'cd nfstream'
         msys2 -c 'cd engine'
         msys2 -c 'gcc -Indpi_includes -shared -o engine_cc.so -g -O2 -Wall engine_cc.c libndpi.a D:/a/_temp/msys64/mingw64/x86_64-w64-mingw32/lib/libws2_32.a /mingw64/lib/libgcrypt.a /mingw64/lib/libgpg-error.a'
         msys2 -c 'rm -rf ndpi_includes/'
         msys2 -c 'cd ..'
         msys2 -c 'cd ..'
         python setup.py bdist_wheel

    - name: Testing and coverage report generation
      run: |
        python -m coverage run tests.py
        python -m coverage combine
