name: windows_build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  release:
    types: [created]
  schedule:
    - cron:  '0 12 * * *'
jobs:
  test:
    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        python-version: [3.9, 3.8, 3.7, 3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Print Python version
      run: |
        python -c "import sys; print(sys.version)"
    - name: Set up NPCAP OEM and SDK
      run: |
         choco install wget --no-progress
         wget --user ${{ secrets.NPCAP_OEM_USERNAME }} --password ${{ secrets.NPCAP_OEM_PASSWORD }} https://nmap.org/npcap/oem/dist/npcap-1.55-oem.exe
         Start-Process npcap-1.55-oem.exe -ArgumentList "/loopback_support=yes /winpcap_mode=yes /dot11_support=yes /S" -wait
         Get-ChildItem 'C:\Program Files\Npcap\' | Sort-Object -Property LastWriteTime
         wget https://nmap.org/npcap/dist/npcap-sdk-1.11.zip
         Expand-Archive -Path npcap-sdk-1.11.zip -DestinationPath npcap-sdk-1.11
         Get-ChildItem | Sort-Object -Property LastWriteTime
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git mingw-w64-x86_64-toolchain automake1.16 automake-wrapper autoconf libtool make mingw-w64-x86_64-json-c
    - name: Build nDPI
      run: |
         msys2 -c 'git clone --branch dev https://github.com/ntop/nDPI.git'
         cd nDPI
         msys2 -c './autogen.sh'
         msys2 -c 'make all'
         msys2 -c 'cp src/lib/libndpi-4.1.0.dll ../nfstream/engine/libndpi.dll'
         msys2 -c 'cd ..'
         msys2 -c 'rm -rf nDPI/'

    - name: Test nDPI
      run: |
        python -m pip install cffi
        cd nfstream
        cd engine
        python test_dll.py
